# Generated by Django 4.1 on 2022-08-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Heading',
            field=models.CharField(max_length=100, null=b'I01\n'),
        ),
        migrations.AlterField(
            model_name='user',
            name='desc',
            field=models.TextField(null=b'I01\n'),
        ),
    ]
