# Generated by Django 4.1 on 2022-08-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_heading_alter_user_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Heading',
        ),
        migrations.RemoveField(
            model_name='user',
            name='desc',
        ),
    ]
