# Generated by Django 4.1 on 2022-08-20 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
